twitter: 
  api_key: Ss0AOAfwgl1Oyzj2SgMiGicZc
  api_key_secret: PZOBLeakrgrtus7gVuNT1DiZ2fv1jgUmSfySeNv1qB7OaL2MBj
  bearer_token: AAAAAAAAAAAAAAAAAAAAAF%2FrhQEAAAAAg8%2FGmLmDxndlu97avYNd3LMY0AA%3Dl6BQe79Gn1RfFFas6UKluWhwYL9UXniU03tjkMoZSK1i5tDdiU


reddit:
  client_id: UHj8J6lSF_CThtSODNDajg
  secret: 2XC26xqun1tstFOBkYxlX7rSWrHj1g

newsapi:
  api_key: ce764671b2534bb3bd509607f5bf8ea2


jwt_secret: Di63RBePO4nUnXp2FNMP2Cz9mPgyo7gSTOh5kVgmHr7rM65k6mfpWzGikS7mmBE

heroku_oauth_token: 64670203-f3f1-4217-ac0d-6b52db3bb1f6

db:  # AWS RDS database
  # database: cointoss
  # user_name: postgres
  # password: GtPbxOqdLh4AhZeFH90i
  # host: cointoss.came1bfngzcs.us-east-1.rds.amazonaws.com
  # port: 5432

  #psql -h cointoss.came1bfngzcs.us-east-1.rds.amazonaws.com -p 5432 -d cointoss -U postgres 
  #GtPbxOqdLh4AhZeFH90i
  host: ec2-52-71-23-11.compute-1.amazonaws.com
  database: d1p6q4h7dhi24a
  user_name: qpgtomdjxijpgm
  password: de8388a3d4fa6b1c957b1f0f9ec6b2ce813879a9a713763cb7c21d1df04b25c5
  port: 5432
  uri: postgres://qpgtomdjxijpgm:de8388a3d4fa6b1c957b1f0f9ec6b2ce813879a9a713763cb7c21d1df04b25c5@ec2-52-71-23-11.compute-1.amazonaws.com:5432/d1p6q4h7dhi24a
  
