twitter: 
  api_key: Ss0AOAfwgl1Oyzj2SgMiGicZc
  api_key_secret: PZOBLeakrgrtus7gVuNT1DiZ2fv1jgUmSfySeNv1qB7OaL2MBj
  bearer_token: AAAAAAAAAAAAAAAAAAAAAF%2FrhQEAAAAAg8%2FGmLmDxndlu97avYNd3LMY0AA%3Dl6BQe79Gn1RfFFas6UKluWhwYL9UXniU03tjkMoZSK1i5tDdiU


reddit:
  client_id: UHj8J6lSF_CThtSODNDajg
  secret: 2XC26xqun1tstFOBkYxlX7rSWrHj1g

newsapi:
  api_key: ce764671b2534bb3bd509607f5bf8ea2


jwt_secret: Di63RBePO4nUnXp2FNMP2Cz9mPgyo7gSTOh5kVgmHr7rM65k6mfpWzGikS7mmBE

db:  # AWS RDS database
  # database: cointoss
  # user_name: postgres
  # password: GtPbxOqdLh4AhZeFH90i
  # host: cointoss.came1bfngzcs.us-east-1.rds.amazonaws.com
  # port: 5432

  #psql -h cointoss.came1bfngzcs.us-east-1.rds.amazonaws.com -p 5432 -d cointoss -U postgres 
  #GtPbxOqdLh4AhZeFH90i

  database: cointoss
  user_name: cointoss
  password: password123
  host: localhost
  port: 5432

  
